"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 20:49:39.569056
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_chb',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_unspsc', sa.String(length=8), nullable=False),
    sa.Column('descripcion_bien', sa.String(length=250), nullable=False),
    sa.Column('unidad_medida', sa.String(length=40), nullable=False),
    sa.Column('precio_referencial_nacional', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_chb_codigo_unspsc'), 'catalogo_chb', ['codigo_unspsc'], unique=True)
    op.create_table('parametros_institucionales',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('partidas_presupuestarias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_partida', sa.String(length=5), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('saldo_disponible', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False),
    sa.Column('programa', sa.String(length=10), nullable=False),
    sa.Column('proyecto', sa.String(length=10), nullable=False),
    sa.Column('actividad', sa.String(length=10), nullable=False),
    sa.Column('fuente', sa.String(length=10), nullable=False),
    sa.Column('organismo', sa.String(length=10), nullable=False),
    sa.Column('monto_aprobado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint("length(codigo_partida) = 5 AND codigo_partida >= '10000' AND codigo_partida <= '49999'", name='ck_partida_clasificador'),
    sa.CheckConstraint('saldo_disponible >= 0', name='ck_partida_saldo_no_negativo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_partida', 'gestion', 'programa', 'proyecto', 'actividad', 'fuente', 'organismo', name='uq_partida_estructura')
    )
    op.create_index(op.f('ix_partidas_presupuestarias_codigo_partida'), 'partidas_presupuestarias', ['codigo_partida'], unique=False)
    op.create_table('secuencias',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('ultimo', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=160), nullable=False),
    sa.Column('cargo', sa.String(length=120), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("rol IN ('ROL_SOLICITANTE', 'ROL_PRESUPUESTO', 'ROL_CONTRATACIONES', 'ROL_RPA', 'ROL_RECEPCION', 'ROL_ADMIN')", name='ck_usuarios_rol'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=60), nullable=False),
    sa.Column('registro_id', sa.String(length=60), nullable=False),
    sa.Column('datos_previos_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('datos_nuevos_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('secuencia', sa.BigInteger(), nullable=False),
    sa.Column('hash_previo', sa.String(length=64), nullable=False),
    sa.Column('hash_registro', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_accion'), 'audit_logs', ['accion'], unique=False)
    op.create_index(op.f('ix_audit_logs_secuencia'), 'audit_logs', ['secuencia'], unique=True)
    op.create_table('contrataciones_menores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correlativo_interno', sa.String(length=30), nullable=False),
    sa.Column('objeto_contratacion', sa.String(length=400), nullable=False),
    sa.Column('tipo_objeto', sa.String(length=20), nullable=False),
    sa.Column('monto_referencial_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('plazo_dias_calendario', sa.Integer(), nullable=False),
    sa.Column('metodo_formalizacion', sa.String(length=20), nullable=True),
    sa.Column('cuce', sa.String(length=40), nullable=True),
    sa.Column('preventivo_c31_nro', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('requiere_excepcion_chb', sa.Boolean(), nullable=False),
    sa.Column('justificacion_excepcion_chb', sa.Text(), nullable=True),
    sa.Column('codigo_autorizacion_chb', sa.String(length=60), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('rpa_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unidad_solicitante', sa.String(length=160), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('especificaciones_tecnicas', sa.Text(), nullable=False),
    sa.Column('lugar_entrega', sa.String(length=200), nullable=False),
    sa.Column('modalidad_cuantia', sa.String(length=30), nullable=True),
    sa.Column('nro_formulario_110', sa.String(length=40), nullable=True),
    sa.Column('fecha_limite_ofertas', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ofertas_abiertas', sa.Boolean(), nullable=False),
    sa.Column('motivo_cierre', sa.Text(), nullable=True),
    sa.Column('ultima_observacion', sa.Text(), nullable=True),
    sa.Column('fecha_adjudicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_formalizacion', sa.Date(), nullable=True),
    sa.CheckConstraint("estado IN ('BORRADOR', 'SOLICITADO', 'CERTIFICADO_PRESUPUESTO', 'EN_COTIZACION', 'EVALUADO', 'ADJUDICADO', 'FORMALIZADO', 'RECEPCIONADO', 'DEVENGADO', 'ANULADO')", name='ck_cm_estado'),
    sa.CheckConstraint("metodo_formalizacion IS NULL OR metodo_formalizacion IN ('ORDEN_COMPRA', 'ORDEN_SERVICIO', 'CONTRATO')", name='ck_cm_metodo'),
    sa.CheckConstraint("modalidad_cuantia IS NULL OR modalidad_cuantia IN ('COMPRA_DIRECTA', 'CONSULTA_PRECIOS_SICOES')", name='ck_cm_modalidad'),
    sa.CheckConstraint("tipo_objeto IN ('BIEN', 'SERVICIO_GENERAL', 'CONSULTORIA', 'OBRA')", name='ck_cm_tipo_objeto'),
    sa.CheckConstraint('monto_referencial_total >= 0 AND monto_referencial_total <= 50000', name='ck_cm_cuantia'),
    sa.CheckConstraint('plazo_dias_calendario >= 1', name='ck_cm_plazo'),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['rpa_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrataciones_menores_correlativo_interno'), 'contrataciones_menores', ['correlativo_interno'], unique=True)
    op.create_index(op.f('ix_contrataciones_menores_estado'), 'contrataciones_menores', ['estado'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_usuario_id'), 'refresh_tokens', ['usuario_id'], unique=False)
    op.create_table('contrataciones_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contratacion_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_unspsc', sa.String(length=8), nullable=False),
    sa.Column('partida_gasto', sa.String(length=5), nullable=False),
    sa.Column('descripcion_especifica', sa.String(length=400), nullable=False),
    sa.Column('unidad_medida', sa.String(length=40), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('precio_unitario_ref', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Uuid(), nullable=True),
    sa.Column('fuera_catalogo_chb', sa.Boolean(), nullable=False),
    sa.Column('estado_chb', sa.String(length=30), nullable=False),
    sa.CheckConstraint("estado_chb IN ('NO_APLICA', 'COMPRA_CHB_OBLIGATORIA', 'EXCEPCION_INCOMPATIBILIDAD', 'SIN_COINCIDENCIA')", name='ck_item_estado_chb'),
    sa.CheckConstraint('cantidad > 0', name='ck_item_cantidad'),
    sa.CheckConstraint('precio_unitario_ref > 0', name='ck_item_precio'),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones_menores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas_presupuestarias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contratacion_id', 'numero', name='uq_item_numero')
    )
    op.create_index(op.f('ix_contrataciones_items_contratacion_id'), 'contrataciones_items', ['contratacion_id'], unique=False)
    op.create_table('cotizaciones_proveedores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contratacion_id', sa.Uuid(), nullable=False),
    sa.Column('nit_ci', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('correo', sa.String(length=160), nullable=False),
    sa.Column('telefono', sa.String(length=40), nullable=False),
    sa.Column('monto_total_ofertado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('plazo_ofertado_dias', sa.Integer(), nullable=False),
    sa.Column('cumple_especificaciones', sa.Boolean(), nullable=False),
    sa.Column('margen_preferencia_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('adjudicado', sa.Boolean(), nullable=False),
    sa.Column('monto_cifrado', sa.LargeBinary(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('registro_preferencia', sa.String(length=20), nullable=False),
    sa.Column('registro_preferencia_valido', sa.Boolean(), nullable=False),
    sa.Column('precio_evaluado', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('recomendada', sa.Boolean(), nullable=False),
    sa.Column('motivo_descalificacion', sa.String(length=300), nullable=True),
    sa.CheckConstraint('margen_preferencia_pct >= 0 AND margen_preferencia_pct <= 100', name='ck_cot_margen'),
    sa.CheckConstraint('plazo_ofertado_dias >= 1', name='ck_cot_plazo'),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones_menores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_proveedores_contratacion_id'), 'cotizaciones_proveedores', ['contratacion_id'], unique=False)
    op.create_table('documentos_expediente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contratacion_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_doc', sa.String(length=40), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=300), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('estado_tramite', sa.String(length=30), nullable=False),
    sa.Column('generado_por_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("tipo_doc IN ('C1_SOLICITUD', 'INFORME_EXCEPCION_CHB', 'CERTIFICACION_C31', 'FICHA_COTIZACION', 'CUADRO_COMPARATIVO', 'NOTA_ADJUDICACION', 'ORDEN_COMPRA_SERVICIO', 'CONTRATO_ADMINISTRATIVO', 'ACTA_RECEPCION_FORM500')", name='ck_doc_tipo'),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones_menores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_expediente_contratacion_id'), 'documentos_expediente', ['contratacion_id'], unique=False)
    op.create_table('preventivos_c31',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contratacion_id', sa.Uuid(), nullable=False),
    sa.Column('partida_id', sa.Uuid(), nullable=False),
    sa.Column('importe', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('ACTIVO', 'LIBERADO', 'DEVENGADO')", name='ck_prev_estado'),
    sa.CheckConstraint('importe > 0', name='ck_prev_importe'),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones_menores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas_presupuestarias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preventivos_c31_contratacion_id'), 'preventivos_c31', ['contratacion_id'], unique=False)
    op.create_table('recepciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contratacion_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=False),
    sa.Column('conforme', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('nro_nia', sa.String(length=30), nullable=True),
    sa.Column('detalle', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dias_retraso', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones_menores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recepciones_contratacion_id'), 'recepciones', ['contratacion_id'], unique=False)
    # ### end Alembic commands ###

    # Audit trail inalterable: se prohibe UPDATE y DELETE sobre audit_logs (solo INSERT)
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            CREATE OR REPLACE FUNCTION audit_logs_inmutable() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs es inalterable: solo se permite INSERT';
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER trg_audit_logs_inmutable
            BEFORE UPDATE OR DELETE ON audit_logs
            FOR EACH ROW EXECUTE FUNCTION audit_logs_inmutable();
        """)
        op.execute("""
            CREATE TRIGGER trg_audit_logs_no_truncate
            BEFORE TRUNCATE ON audit_logs
            FOR EACH STATEMENT EXECUTE FUNCTION audit_logs_inmutable();
        """)


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_no_truncate ON audit_logs")
        op.execute("DROP TRIGGER IF EXISTS trg_audit_logs_inmutable ON audit_logs")
        op.execute("DROP FUNCTION IF EXISTS audit_logs_inmutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recepciones_contratacion_id'), table_name='recepciones')
    op.drop_table('recepciones')
    op.drop_index(op.f('ix_preventivos_c31_contratacion_id'), table_name='preventivos_c31')
    op.drop_table('preventivos_c31')
    op.drop_index(op.f('ix_documentos_expediente_contratacion_id'), table_name='documentos_expediente')
    op.drop_table('documentos_expediente')
    op.drop_index(op.f('ix_cotizaciones_proveedores_contratacion_id'), table_name='cotizaciones_proveedores')
    op.drop_table('cotizaciones_proveedores')
    op.drop_index(op.f('ix_contrataciones_items_contratacion_id'), table_name='contrataciones_items')
    op.drop_table('contrataciones_items')
    op.drop_index(op.f('ix_refresh_tokens_usuario_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_contrataciones_menores_estado'), table_name='contrataciones_menores')
    op.drop_index(op.f('ix_contrataciones_menores_correlativo_interno'), table_name='contrataciones_menores')
    op.drop_table('contrataciones_menores')
    op.drop_index(op.f('ix_audit_logs_secuencia'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_accion'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('secuencias')
    op.drop_index(op.f('ix_partidas_presupuestarias_codigo_partida'), table_name='partidas_presupuestarias')
    op.drop_table('partidas_presupuestarias')
    op.drop_table('parametros_institucionales')
    op.drop_index(op.f('ix_catalogo_chb_codigo_unspsc'), table_name='catalogo_chb')
    op.drop_table('catalogo_chb')
    # ### end Alembic commands ###
